# Form implementation generated from reading ui file 'e:\Automate\PythonUI\OneMore\app\view\ui\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 680)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ScrollArea = ScrollArea(parent=self.centralwidget)
        self.ScrollArea.setGeometry(QtCore.QRect(120, 10, 691, 611))
        self.ScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ScrollArea.setWidgetResizable(False)
        self.ScrollArea.setObjectName("ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1000, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.CardWidget1 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1.setGeometry(QtCore.QRect(70, 40, 731, 51))
        self.CardWidget1.setObjectName("CardWidget1")
        self.CardWidget1_2 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_2.setGeometry(QtCore.QRect(70, 110, 731, 51))
        self.CardWidget1_2.setObjectName("CardWidget1_2")
        self.CardWidget1_3 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_3.setGeometry(QtCore.QRect(70, 180, 731, 51))
        self.CardWidget1_3.setObjectName("CardWidget1_3")
        self.CardWidget1_4 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_4.setGeometry(QtCore.QRect(70, 250, 731, 51))
        self.CardWidget1_4.setObjectName("CardWidget1_4")
        self.CardWidget1_5 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_5.setGeometry(QtCore.QRect(70, 320, 731, 51))
        self.CardWidget1_5.setObjectName("CardWidget1_5")
        self.CardWidget1_6 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_6.setGeometry(QtCore.QRect(70, 390, 731, 51))
        self.CardWidget1_6.setObjectName("CardWidget1_6")
        self.CardWidget1_7 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_7.setGeometry(QtCore.QRect(70, 450, 731, 51))
        self.CardWidget1_7.setObjectName("CardWidget1_7")
        self.CardWidget1_8 = CardWidget(parent=self.scrollAreaWidgetContents)
        self.CardWidget1_8.setGeometry(QtCore.QRect(70, 520, 731, 51))
        self.CardWidget1_8.setObjectName("CardWidget1_8")
        self.ScrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from qfluentwidgets import CardWidget, ScrollArea

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
