name: Tag Workflow
on:
  push:
    # 使用tags/*来监听所有的tag事件
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code with current tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:
          #python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Build project with Nuitka-Action
      #   uses: Nuitka/Nuitka-Action@main
      #   with:
      #     nuitka-version: 2.4.8
      #     script-name: main.py
      #     standalone: true
      #     enable-plugins: pyqt6
      #     windows-console-mode: disable
      #     windows-icon-from-ico: app/resource/images/logo.ico
      #     #lto: yes
      #     mingw64: yes
      #     show-memory: yes
      #     show-progress: yes
      #     include-data-dir: app/resource=app/resource
      #     assume-yes-for-downloads: yes
      #     onefile: false
      #     nofollow-import-to: tools
      - name: Build project with nuitka
        run: |
          python deploy.py

      - name: Get tag name
        id: get_tag
        run: |
          $current_tag = git describe --tags --abbrev=0 HEAD
          echo "tag=${current_tag}" >> $env:GITHUB_ENV

      # - name: Get previous tag name
      #   id: get_previous_tag
      #   run: |
      #     $previous_tag = git describe --tags --abbrev=0 HEAD^
      #     echo "previous_tag=${previous_tag}" >> $env:GITHUB_ENV

      - name: Compress files
        run: |
          mkdir -p dist/onemore
          cp -r build/main.dist/* dist/onemore/
          cp -r app/resource dist/onemore/app/resource
          cp -r plugins dist/onemore/plugins
          Compress-Archive -Path dist/onemore -DestinationPath dist/onemore.zip
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false

          # body: |
          #   Changes in this Release
          #   https://github.com/miniLQ/onemore/compare/${{ env.previous_tag }}...${{ env.tag }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/onemore.zip
          asset_name: onemore.zip
          asset_content_type: application/zip

      # - name: upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows Build
      #     tagname: ${{ steps.get_tag.outputs.tag }}
      #     path: release/onemore_${{ tagname }}.zip 